// Mock data for users
export const users = [
  {
    id: 'u1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'Admin',
    status: 'Active',
    lastActive: '2 minutes ago',
    decks: 12,
    joined: 'Jan 15, 2024',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'u2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'User',
    status: 'Active',
    lastActive: '1 hour ago',
    decks: 8,
    joined: 'Jan 20, 2024',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'u3',
    name: 'Robert Johnson',
    email: 'robert.johnson@example.com',
    role: 'User',
    status: 'Inactive',
    lastActive: '2 days ago',
    decks: 5,
    joined: 'Feb 1, 2024',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'u4',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    role: 'Curator',
    status: 'Active',
    lastActive: '3 hours ago',
    decks: 15,
    joined: 'Dec 10, 2023',
    avatar: '/placeholder.svg?height=40&width=40',
  },
  {
    id: 'u5',
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    role: 'User',
    status: 'Suspended',
    lastActive: '1 week ago',
    decks: 3,
    joined: 'Jan 5, 2024',
    avatar: '/placeholder.svg?height=40&width=40',
  },
]

// Mock data for decks
export const decks = [
  {
    id: 'd1',
    name: 'JavaScript Basics',
    creator: 'John Doe',
    cards: 48,
    status: 'Published',
    reported: false,
    views: 1245,
    created: 'Jan 15, 2024',
    lastUpdated: 'Feb 2, 2024',
  },
  {
    id: 'd2',
    name: 'React Fundamentals',
    creator: 'Jane Smith',
    cards: 35,
    status: 'Published',
    reported: false,
    views: 890,
    created: 'Jan 20, 2024',
    lastUpdated: 'Feb 1, 2024',
  },
  {
    id: 'd3',
    name: 'Inappropriate Content',
    creator: 'Michael Wilson',
    cards: 12,
    status: 'Under Review',
    reported: true,
    views: 45,
    created: 'Feb 1, 2024',
    lastUpdated: 'Feb 3, 2024',
  },
  {
    id: 'd4',
    name: 'CSS Properties',
    creator: 'Emily Davis',
    cards: 50,
    status: 'Published',
    reported: false,
    views: 720,
    created: 'Dec 15, 2023',
    lastUpdated: 'Jan 25, 2024',
  },
  {
    id: 'd5',
    name: 'Spam Content',
    creator: 'Unknown User',
    cards: 5,
    status: 'Blocked',
    reported: true,
    views: 10,
    created: 'Feb 2, 2024',
    lastUpdated: 'Feb 3, 2024',
  },
]

// Mock data for reports
export const reports = [
  {
    id: 'r1',
    type: 'Deck',
    item: 'Inappropriate Content',
    reporter: 'Jane Smith',
    reason: 'Contains offensive language',
    status: 'Pending',
    date: 'Feb 3, 2024',
  },
  {
    id: 'r2',
    type: 'User',
    item: 'Michael Wilson',
    reporter: 'John Doe',
    reason: 'Spam content creation',
    status: 'Resolved',
    date: 'Feb 2, 2024',
  },
  {
    id: 'r3',
    type: 'Deck',
    item: 'Spam Content',
    reporter: 'Emily Davis',
    reason: 'Promotional content violating terms',
    status: 'Pending',
    date: 'Feb 3, 2024',
  },
  {
    id: 'r4',
    type: 'Comment',
    item: 'Comment on JavaScript Basics',
    reporter: 'Robert Johnson',
    reason: 'Harassment',
    status: 'Under Review',
    date: 'Feb 1, 2024',
  },
]
